/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('./src/components/ui/accordion/accordion.vue')['default']
    AccordionContent: typeof import('./src/components/ui/accordion/accordion-content.vue')['default']
    AccordionItem: typeof import('./src/components/ui/accordion/accordion-item.vue')['default']
    AccordionTrigger: typeof import('./src/components/ui/accordion/accordion-trigger.vue')['default']
    Button: typeof import('./src/components/ui/button.vue')['default']
    ILucideChevronDown: typeof import('~icons/lucide/chevron-down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiAccordion: typeof import('~/components/ui/accordion/accordion.vue')['default']
    'UiAccordion-Item': typeof import('./src/components/ui/accordion/accordion-item.vue')['default']
    'UiAccordion-Trigger': typeof import('./src/components/ui/accordion/accordion-trigger.vue')['default']
    UiAccordionContent: typeof import('~/components/ui/accordion/accordion-content.vue')['default']
    UiAccordionItem: typeof import('~/components/ui/accordion/accordion-item.vue')['default']
    UiAccordionTrigger: typeof import('~/components/ui/accordion/accordion-trigger.vue')['default']
    UiButton: typeof import('./src/components/ui/button.vue')['default']
  }
}
